version: "~> 1.0"
git:
    depth: 1
    quiet: true
language: java
jdk:
    - openjdk21
branches:
    only:
        - develop
        - support/4.1
cache:
    directories:
        - "$HOME/.m2"
notifications:
    slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
before_install:
    - mkdir -p $HOME/.m2
    - cp .travis-settings.xml $HOME/.m2/settings.xml
install: skip
script:
    - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then bash -c "mvn deploy --settings .travis-settings.xml"; fi
    - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then bash -c "mvn clean install"; fi
env:
    global:
        - secure: "boWodGpeilkihEmFzJ7zHKiSyAuQsxH4YeGvoTA8ZgcVNoc2TYFcMXpMSXHBOfWXEgmsW7Y8+6Lny9F8MMhK6KAGRU/PukETqpSe8+rCCY5ewST/gQbRw4QW+23vurXeidWucdHNxHz3Y2r83WAkhN5NOEkJzEwq3YGWObO3crw="
        - secure: "48LgzFJuV8V4C6hbjtmoog/PAp3GvkyPGNiSczRmwKo8Ps5oOqUV61rZLJpXcdaGctJcP7Rf8WycD9PntgRsfQaMCqIyESCYTY82BrrRcvQ5m4Xvz/J+hxoh9ZPMO02f75nVua97ysu0DkPWjpNeTEkx8d1kWSrcxFlzQ7M85Ro="
