language: java
jdk:
- openjdk11
branches:
  only:
  - develop
  - support/.*
  - master
notifications:
  irc:
    channels:
    - chat.freenode.net#craftercms
    use_notice: true
    skip_join: true
  slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
script:
- if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then bash -c  "mvn deploy --settings
  .travis-settings.xml";  fi
- if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then bash -c "mvn clean install" ;fi
env:
  global:
  - secure: CN6Zsr3CyCd5XRdP5p0Aqq51C4vsMlSmSwI1Z1JesCEWjpiO23EtzW6rhTk5bNFi9yuaTEjfHE8RzU75y7iNSOjU7xG/X5QWYsXyfWnZ2BSX/tRDEQOs6X8evVV2fpYLM3aQE/6WEOrCNjMNSOQ2HQYVFq6wWrlOYG39NZPCE72EjGaMaYGQX7M9Jckex2u1VdhB2zOLkr8il6LbXvqSemAQ/tE8otsnk4ZeJJdZdogJNt/3fTXTDrkrWox8I0UHxNjoJuwo0apVNPUYFIjAeyyMYdnM/j0Kw3h8jcGWRF3tCs7rkF8uGpONkJ2O+aJA/rZ5s6dRVgtxkoQ9Nbyu5zrWdCuj/Xe5VLkH6ToTWRURMlyyILv2k22MljkEAsVxa2EKtk67XzCH7gPVthfiaDPa+rb+O02Ru27U7MM6MbpTLKlSASqIQ2KLIdRT24S8Ccb/iF1f575vpqah9Ae03YOQAZpQmE7+9z4irOvpXocdLG55MgLLYbnFLg1AB2t0+a78a5/hToeAb+mVWpIoKCELclzsI8HPVUyz24+MjHPynIj6VNnGmMe38lB0rJ8E5eGRFkzbJeccPZQM09djHRkmXdYjdt4rZWeDEi/J2PhnQ8snekUqgK8xF8X12Nnka0lUJiAfSLqU+Hm8iuTzcfL7J6zorOErCVIXXEmabHQ=
  - secure: C3zFAsR1bxgVIMx9RJhHWETcRpP6wah60qitK6J9t3lEvK9oyYckA0xgEj8Jimn4aiqgoTMHVog00H5mHcH95v5KmHdKpEa9NQe3EHqmK0w3qyfsqCJ2Djvsh3DDh1k0ZFarpJyL8gIBobUP7e0HBOYRkuJUja7P3T6LSd71B0/zkQFAJZcqOJKBCkYdZDdsYkOdNGM/7EqVwCRoVlx8O1lYxtAESHJzJAEBsTjU6GUX+nPhZor2BcgQbnsVnS9Jeo9Arhtp/7zhGfCVh/UBSqTkxaH2u0aC4qcL42Pi9p1wetVRfT5/+9LMTMnSsR3aQ6GuEyssZXJoc8Mr8uqXf7BUik3JVC2va+gmO6M0XkBNoG20h3gSrf7NkI/V7PmsRGLrPwzSaWv9gAE6YDfGca2Dro/+sYtO4qkqqionowULE3wVBSdmyFDrWHPNxXWMqlRjEvXYl0+dzuIcEQa7IEdYeico3Xtc7ceaemEO3GZq27LFSNu/5iqHRJ8u8LpjKu3ME9+IifvKN843gF9XYeO4E7jC9broGPGC8/8Bh4kdWViz6QHyZhk+YmX9vHh42ouyn6qWaFD5xAqoyItzjp7la9cfEEwB6TY7P2xtfXYCgQpEMWx++mh+eARIZA4U7WOEdX2yOA1z22wkOfSNDR7Wy9OKSKHG9BflskiNx6c=
