language: java
jdk:
- openjdk8
branches:
  except:
  - travis
notifications:
  irc:
    channels:
    - chat.freenode.net#craftercms
    use_notice: true
    skip_join: true
  slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
env:
  global:
  - secure: Pcq7Sd3Y0irRbiEG2qKs63aN0BzGXtKV18/TLyIHIkEaHx6bgrQZ68EwvHBW/lwitvPIl2l8X1UwaziKCGPv0XhKt+hfuMzfiPIQhoPMkgLwFJUoGR9A4TqrRIP+iEuksT+2zP5fSBQiY4V+pwtXk9DrYBaocjZYJHYodHosFXk=
  - secure: gAkAjopP5JErUsTbmySaUpCBM/VLmQKQpy9N7noKRxPrHBD80BtoQoLgz18X1+DT13AUJKkhPZ++dNmby3cTsQechrZ3bL6z2+Y6l882GzXlB0Ebx1gG78IfqqSAEEJYsJsSMi0Leo9kAlt6ckuxcrt4u45Woo+Y972fIV1PEY0=
before_install: git clone -b travis `git config --get remote.origin.url` target/travis
script:
- if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then bash -c  "mvn deploy --settings
  target/travis/settings.xml";  fi
- if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then bash -c "mvn clean install" ;fi
