version: "~> 1.0"
git:
    depth: 1
    quiet: true
language: java
jdk:
    - openjdk21
branches:
    only:
        - develop
        - support/4.x
cache:
    directories:
        - "$HOME/.m2"
notifications:
    slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
before_install:
    - mkdir -p $HOME/.m2
    - cp .travis-settings.xml $HOME/.m2/settings.xml
install: skip
script:
    - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then bash -c "mvn deploy --settings .travis-settings.xml"; fi
    - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then bash -c "mvn clean install"; fi
env:
    global:
        - secure: "VyAxWGGnskrd2qdoZX3IKhZ9nVG4aiLJbM+lBP9XW6cmxtqnLH7zOWwfErnZYcpE97W+jfJVVxV7N+RFwWmc6FSJDoaFoqDs7aEmTUpvwuybyPIHHyOzpfb0V6cVWp3WITZTSW4PoKs5oWK8pbI+3UczUL+HEz7zhXBj0GotcJY="
        - secure: "jYoLNFMoUfBvBHlwPQwjksVteJNEBYwkqY7ndNkgtfmJdM+dvSQO8nKb3mmFlIXREMcQDipA7UVMCS5sS855ue0m7z15snshT9FYcnsUafFdaUc34/QE96aw20VlVbXGSG4OFDARrTE2Xikf78n9hjyzCWshxebX9GZhhnXDLE4="
