language: java
jdk:
- openjdk11
branches:
  only:
  - develop
  - support/.*
  - master
notifications:
  irc:
    channels:
    - chat.freenode.net#craftercms
    use_notice: true
    skip_join: true
  slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
script:
- if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then bash -c  "mvn deploy --settings
  .travis-settings.xml";  fi
- if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then bash -c "mvn clean install" ;fi
env:
  global:
  - secure: 8ohuI1p9Ze2xp/z6ovaRrAE3Ns0imaFCBuhG/uuNr3qsiBHkAu9I+2N3jo90Zj1+Cyhx76fcIeweaOSgQIPlaBA7d4oKyRUyqM7ZS4S3537HoU4itfK8O51FBsMR/XZcuG8qHmlPlY6PsXfAaw1U5jHamWi1wTbAtoEJiIRcy50=
  - secure: RAZAritD7x2RXJ6NkN+zG8JcLTg1WWr0KBVksA2Lt8bPpgRHyAHwfaNvWqQaXCBxsHXJnljvP3x4IyVJZkaACV1L3p2qjpSsA1jmRjNcP/wg9aD9S3iYDUwWQUBMxeTBIDx8ghF6Jf0Tx6KhtiOPE4km+Am+V7oPHdaXyKONH3k=
