version: "~> 1.0"
git:
  depth: 1
  quiet: true
language: java
jdk:
  - openjdk17
branches:
  only:
    - develop
    - support/4.1.x
    - support/4.0.x
    - master
cache:
  directories:
    - "$HOME/.m2"
notifications:
  slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
before_install:
  - mkdir -p $HOME/.m2
  - cp .travis-settings.xml $HOME/.m2/settings.xml
install: skip
script:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then bash -c "mvn deploy --settings .travis-settings.xml"; fi
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then bash -c "mvn clean install"; fi
env:
  global:
    - secure: "TCUSE7dMS65B4c0T7x5PcUpm8536Jap/FEcGZnnDzhA6YwCcLLf5INNfIZ1pdIilh26d1sF66B7K1uD1pSgEFRfjApVV9zJZz/SGbbBJazuLshN96+bPGkzUGOqmGtI1IA9+qIWe0DzyR0Lw7bWVcslzlWfmJ+woGJkKaMiIFq8="
    - secure: "2e6QpfKlDb3uIGuW8QfIAncAabqwV6R70sxBjgFbpj98EAl9DKxjC1F4K4amhKjCUptKtsuBmboggsD+iba7lRuo2zXklN3FY8ET+Ac7a7HKKQxmkF1JN1OeQbCzKl9EReZ8r55fEdul6wBDsJ/V729pURiYjIJv5P9aThrKxLE="
